// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.4
// source: proto/genshin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenshiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GenshiRequest) Reset() {
	*x = GenshiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_genshin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenshiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenshiRequest) ProtoMessage() {}

func (x *GenshiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_genshin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenshiRequest.ProtoReflect.Descriptor instead.
func (*GenshiRequest) Descriptor() ([]byte, []int) {
	return file_proto_genshin_proto_rawDescGZIP(), []int{0}
}

func (x *GenshiRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GenshiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Body    string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *GenshiResponse) Reset() {
	*x = GenshiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_genshin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenshiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenshiResponse) ProtoMessage() {}

func (x *GenshiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_genshin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenshiResponse.ProtoReflect.Descriptor instead.
func (*GenshiResponse) Descriptor() ([]byte, []int) {
	return file_proto_genshin_proto_rawDescGZIP(), []int{1}
}

func (x *GenshiResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GenshiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GenshiResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_proto_genshin_proto protoreflect.FileDescriptor

var file_proto_genshin_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x73, 0x68, 0x69, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x6d, 0x61, 0x70, 0x6c, 0x65, 0x2e, 0x6e, 0x6f, 0x74,
	0x65, 0x2e, 0x67, 0x65, 0x6e, 0x73, 0x68, 0x69, 0x22, 0x1f, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x73,
	0x68, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x52, 0x0a, 0x0e, 0x47, 0x65, 0x6e,
	0x73, 0x68, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x32, 0x5e, 0x0a,
	0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d,
	0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x20, 0x2e, 0x6d, 0x61, 0x70, 0x6c, 0x65,
	0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x67, 0x65, 0x6e, 0x73, 0x68, 0x69, 0x2e, 0x47, 0x65, 0x6e,
	0x73, 0x68, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6d, 0x61, 0x70,
	0x6c, 0x65, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x67, 0x65, 0x6e, 0x73, 0x68, 0x69, 0x2e, 0x47,
	0x65, 0x6e, 0x73, 0x68, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_genshin_proto_rawDescOnce sync.Once
	file_proto_genshin_proto_rawDescData = file_proto_genshin_proto_rawDesc
)

func file_proto_genshin_proto_rawDescGZIP() []byte {
	file_proto_genshin_proto_rawDescOnce.Do(func() {
		file_proto_genshin_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_genshin_proto_rawDescData)
	})
	return file_proto_genshin_proto_rawDescData
}

var file_proto_genshin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_genshin_proto_goTypes = []interface{}{
	(*GenshiRequest)(nil),  // 0: maple.note.genshi.GenshiRequest
	(*GenshiResponse)(nil), // 1: maple.note.genshi.GenshiResponse
}
var file_proto_genshin_proto_depIdxs = []int32{
	0, // 0: maple.note.genshi.SearchService.Search:input_type -> maple.note.genshi.GenshiRequest
	1, // 1: maple.note.genshi.SearchService.Search:output_type -> maple.note.genshi.GenshiResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_genshin_proto_init() }
func file_proto_genshin_proto_init() {
	if File_proto_genshin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_genshin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenshiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_genshin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenshiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_genshin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_genshin_proto_goTypes,
		DependencyIndexes: file_proto_genshin_proto_depIdxs,
		MessageInfos:      file_proto_genshin_proto_msgTypes,
	}.Build()
	File_proto_genshin_proto = out.File
	file_proto_genshin_proto_rawDesc = nil
	file_proto_genshin_proto_goTypes = nil
	file_proto_genshin_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchServiceClient interface {
	Search(ctx context.Context, in *GenshiRequest, opts ...grpc.CallOption) (*GenshiResponse, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) Search(ctx context.Context, in *GenshiRequest, opts ...grpc.CallOption) (*GenshiResponse, error) {
	out := new(GenshiResponse)
	err := c.cc.Invoke(ctx, "/maple.note.genshi.SearchService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
type SearchServiceServer interface {
	Search(context.Context, *GenshiRequest) (*GenshiResponse, error)
}

// UnimplementedSearchServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSearchServiceServer struct {
}

func (*UnimplementedSearchServiceServer) Search(context.Context, *GenshiRequest) (*GenshiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	s.RegisterService(&_SearchService_serviceDesc, srv)
}

func _SearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenshiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/maple.note.genshi.SearchService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Search(ctx, req.(*GenshiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "maple.note.genshi.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/genshin.proto",
}
